// <auto-generated />
using System;
using CleanArchitecture.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleanArchitecture.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240519120114_AddAsesore")]
    partial class AddAsesore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            
            modelBuilder.Entity("CleanArchitecture.Domain.Entities.Asesore", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Apellido")
                    .IsRequired()
                    .HasColumnType("nvarchar(100)");

                b.Property<bool>("Deleted")
                    .HasColumnType("bit");

                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasMaxLength(250)
                    .HasColumnType("nvarchar(250)");

                b.HasKey("Id");

                b.ToTable("Asesores");

                b.HasData(
                    new
                    {
                        Id = new Guid("b642bf25-134c-47a2-a0df-84ed14d03c43"),
                        Apellido = "canales",
                        Deleted = false,
                        Nombre = "marcos"
                    });
            });

            
#pragma warning restore 612, 618
        }
    }
}
